---
contact_links:
  - name: ðŸ‘¨â€ðŸ‘¨â€ðŸ‘¦â€ðŸ‘¦ Ask a question on github
    url: https://github.com/minecraftmultiplayer/maven/discussions/
    about: Ask questions and discuss with other community members.
  - name: ðŸ’¬ Discord Chat
    url: https://discord.gg/CHANGEME_MANUAL
    about: >
      Ask questions and talk to other maven users and the maintainers.

  - name: ðŸ“§ Email
    url: https://mailxto.com/CHANGEME_MANUAL
    about: Send me an email if you wanna say more or talk privately.